# TODO: Optional, try to make this work
version: '3'
services:
  test:
    build: .
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/versateach
      - ./java_sdk:/java_install
    ports:
      - "80:80"
      # The DNS server works within container (dig @localhost example.com), but
      # *not* via published port. Not sure this is related to systemd.
      #- "53:53/tcp"
      #- "53:53/udp"
